name: chefsanjay
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: master
      deploy_on_push: true
      repo: sanjikasehgal/chefsanjay
    name: chefsanjay
    routes:
      - path: /
    source_dir: /dist
    index_document: index.html
